// Data of projects
const projects = [
  {
    id: 0,
    title: "Text-Play",
    image: "/capture.png",
    desc: "This is the text app for textual manipulations.",
    tech: ["React", "Bootrstrap"],
    link: "https://my-first-react-app-text-analyzer.vercel.app/",
    github: "https://github.com/Wiwek09/My-First-React-App-Text-Analyzer",
  },
  {
    id: 1,
    title: "GaintPlay-Clone",
    image: "/gaintplay.png",
    desc: "This is the design of online gaming platform, Gaintplay.",
    tech: ["React", "Next", "React-Hook-Form"],
    link: "https://gaintplay.vercel.app/",
    github: "https://github.com/Wiwek09/Gaintplay",
  },
  {
    id: 2,
    title: "E-commerce",
    image: "/ecommerce.png",
    desc: "E-Commerce App. It contains only design part. Backend and full integration are in github repo",
    tech: ["React", "JWT", "Stripe", "Express", "MongoDB"],
    link: "https://e-commerce-front-end-agez.vercel.app/",
    github: "https://github.com/Wiwek09/E-COMMERCE-FULLSTACK",
  },
  {
    id: 3,
    title: "ChatAPP",
    image: "/chatapp.png",
    desc: "Online chatting app where users can chat having same room identification",
    tech: ["React", "Next", "Socket.io", "Express"],
    link: "https://chat-app-using-react-socket.vercel.app/",
    github: "https://github.com/Wiwek09/Chat-App-Using-React-Socket",
  },
  {
    id: 4,
    title: "ToDo",
    image: "/todo.png",
    desc: "ToDo application where users can add,edit and delete the task they assign",
    tech: ["React", "Hooks"],
    link: "https://todolist-rho-green.vercel.app/",
    github: "https://github.com/Wiwek09/TodoList-Web-App",
  },
  {
    id: 5,
    title: "EPL Players Data Analytics",
    image: "/epl.png",
    desc: "This is the project of data analytics where insights are drawn from given data set of English Premier league football Players.",
    tech: [
      "Python",
      "NumPy",
      "Pandas",
      "MatPlotLib",
      "Seaborn",
      "Jupyter notebook",
    ],
    link: "https://github.com/Wiwek09/EPL-Data-Analytics/blob/master/Data-Visualization.ipynb",
    github: "https://github.com/Wiwek09/EPL-Data-Analytics",
  },
  {
    id: 6,
    title: "Online Clothing Store",
    image: "/image.png",
    desc: "Online shopping store where users can watch, search and see details of the products.",
    tech: ["Next", "FakestoreApi", "TanStack Query"],
    link: "https://online-commerce.vercel.app/",
    github: "https://github.com/Wiwek09/Online-Commerce",
  },
];

export const skills = [
  "HTML",
  "CSS",
  "Tailwind",
  "Javascript",
  "Typescript",
  "Python",
  "React",
  "Next",
  "Node",
  "Express",
  "MongoDB",
  "RestAPI",
  "MySQL",
];

export default projects;
